### ISSUE TITLE
Multiple registration results for one sequence

### ISSUE THREAD

**Issue by AfterJourney00** [xiexh20/behave-dataset#18]
Hi, thank you for your excellent work!

I found that some sequences like `Date02_Sub02_monitor_move` and `Date04_Sub05_monitor` have multiple registration results in `behave-30fps-params-v1/`(e.g. `behave-30fps-params-v1/Date02_Sub02_monitor_move` and `behave-30fps-params-v1/Date02_Sub02_monitor_move2`). I wonder what's the differences between them and which one should be treated as the ground truth.

Thanks a lot!

**Comment by xiexh20** [comment]
Hi,

This is due to the difficulty of registrating the intermediate frames between these two parts. In these frames, the object PC is too incomplete and it was not possible to obtain registration over the full sequence. Hence I split it into two sequences. 
You can find the correspondence from the parameters to RGBD images by the 'frame_times' stored in each npz file. The frame time list should have the same length as the number of parameters in each npz file. 

Best,
