### ISSUE TITLE
Fail to run video2image.py with -nodepth arg on Date06_Sub07_backpack_back

### ISSUE THREAD

**Issue by AfterJourney00** [xiexh20/behave-dataset#19]
Hi,

I tried to run `video2image.py` to extract images from videos, and all things work well except `Date06_Sub07_backpack_back`. 

The error info shows that:
![Screen Shot 2023-01-13 at 13 39 22](https://user-images.githubusercontent.com/62049842/212245482-39e112ea-43f6-40a8-a7b4-bea7f6a33f4f.png)

Is this due to synchronization problem or my mistake? Could you please have a check on this sequence?

Thanks a lot!

**Comment by AfterJourney00** [comment]
This error also occurs on sequence `Date07_Sub08_boxtiny`.

**Comment by AfterJourney00** [comment]
This error also occurs on `Date07_Sub08_boxtiny`.

**Comment by xiexh20** [comment]
Hi,

This is due to a synchronization error. 
For this sequence, one kinect actually started recording at time 3.23s. I originally set if the query frame time is 0.2s earlier than the first frame, it is invalid. Hence if the query frame time is t3.0s, it will report an error. 
It is easy to fix this by increase the threshold in [this line](https://github.com/xiexh20/behave-dataset/blob/main/data/video_reader.py#L82).

For starting frames, the motion usually is not very fast. Therefore, the synchronization problem won't cause severe problems. It should be fine if you just increase the threshold for these sequences you mentioned.
