### ISSUE TITLE
30fps Registration result of several sequences are misaligned with the rgbd data

### ISSUE THREAD

**Issue by AfterJourney00** [xiexh20/behave-dataset#20]
Hi,

I found that the registration result in `behave-30fps-params-v1/` of the following sequences are misaligned with corresponding rgbd data in time series(e.g. the sequence length are different), and no information about how to align them is released(e.g. the registration result starts at which frame and end at which frame according to the rgbd sequence).
![4741673882203_ pic](https://user-images.githubusercontent.com/62049842/212713209-6bc31125-23ae-4f60-85d0-b0534d6c7d03.jpg)

I hope these sequences can be checked and some information about how to align registration result with rgbd data in time series can be reported. Thank you!

**Comment by xiexh20** [comment]
Hi,

You can find the correspondence of the parameters to RGBD images by the 'frame_times' stored in each npz file. 
Note that NOT all frames have registration results due to synchronization problem between kinects or incomplete PC, as also discussed in [this issue](https://github.com/xiexh20/behave-dataset/issues/18).

Best,
