### ISSUE TITLE
One frame more registration result than rgbd data

### ISSUE THREAD

**Issue by AfterJourney00** [xiexh20/behave-dataset#21]
Hi,

I found that the following sequences have one frame more registration result than corresponding rgbd data(e.g. both of them start at frame `t0003.000`, then registration result ends at frame `t0050.433` but rgbd data ends at frame `t0050.400`). Should I just ignore the registration result at `t0050.433` or any special operations should be taken to address this problem? 
![Screen Shot 2023-01-17 at 15 45 50](https://user-images.githubusercontent.com/62049842/212838832-8c0ab412-f8cf-4e40-8a58-78c167fe3fc9.png)

And I wonder how the "one frame more" registration result is fitted without corresponding rgbd data?

Thanks a lot!

**Comment by xiexh20** [comment]
Hi,

Thanks for pointing out this. 
Yes, you can just ignore this registration. Other frames are synchronized well. 
It is due to a small difference on frame extraction. Currently, the last frame time is set as the minimum ending time of all kinects. But when I did the registration, the last frame time a bit longer (probably the longest or average ending time). Hence I got one more frame and obtained registration for that as well. 
Again, the motion is usually slow towards the end of the sequence. Therefore registration is still possible with tiny synchronization problem between kinects.

Best,
