### ISSUE TITLE
The keyboard and basketball's mask seems to be missing.

### ISSUE THREAD

**Issue by kaenkogashi** [xiexh20/behave-dataset#22]
Thank you very much for your BEHAVE dataset.

As with BEHAVE, each frame contains a person and object mask. However, there appear to be few keyboard and basketball masks.

https://virtualhumans.mpi-inf.mpg.de/behave/license.html
>Human and object segmentation masks:
>[part1 (~7GB)](https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/masks/masks-date01-02.tar)
>[part2 (~10GB)](https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/masks/masks-date03.tar)
>[part3 (~10GB)](https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/masks/masks-date04-06.tar)
>[part4 (~7GB)](https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/masks/masks-date07.tar)

I download human and object segmentation masks from upper URL, but only find few segmentation masks of keyboard and basketball.

Would you upload all mask of keyboard and basketball in the video data?

**Comment by xiexh20** [comment]
Hi, thanks for your interest.

Indeed, the basketball and keyboard masks are missing. This is because the registration for these sequences at 30fps was too difficult, hence we did not register them. Therefore, you won't have object masks for them as well. 

You can find a list of all sequences with 30fps registrations here: 
https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/behave-30fps-error_frames.json
where `error_seqs` are sequences with possibly a few errors and `good_quality` are sequences with good registration quality.
