### ISSUE TITLE
Mismatch between number of frames for object_fit_all.pkl and smpl_fit_all.pkl

### ISSUE THREAD

**Issue by connorzl** [xiexh20/behave-dataset#30]
Hi, I noticed that for some sequences, the number of frames in object_fit_all.pkl and smpl_fit_all.pkl is not the same.

I downloaded the SMPL and object parameters here: https://datasets.d2.mpi-inf.mpg.de/cvpr22behave/behave-30fps-params-v1.tar

Is this intended? The number of object frames is always less than the number of human frames, so should I only be processing up to the number of object frames?

**Comment by xiexh20** [comment]
Hi, 

Thank you for your interests.
Can you point out which sequence(s) have this problem? I will dig it a bit deepeer and figure out the problem. Thanks!

**Comment by connorzl** [comment]
Hi,

Thanks for the response! The two sequences that have this problem (number of object frames != number of human frames) are Date02_Sub02_backpack_twohand and Date06_Sub07_backpack_back

I found this by comparing the number of frames contained in "smpl_fit_all.npz" and "object_fit_all.npz" for each scene.

**Comment by xiexh20** [comment]
Thank you for pointing them out. 
Indeed these two sequences have mismatch between SMPL and object frames, this is because some frames were removed due to poor object registrations. But the SMPL parameters were not updated to also reflect the removal.

Yes, you can just process up to the number of object frames. 

I have update these mismatched sequences, everything should be fine now. 

Best,
Xianghui
